function [] = bulk_plotting(md_struct, super_title, i, res, table, zoom, cval)
    md_budd_present = loadmodel('Models/accepted_models/Model_kangerlussuaq_budd.mat');
    md_budd = loadmodel('Models/kg_budd_lia.mat'); % lia

    md1 = md_struct{1};
    md2 = md_struct{2};
    md3 = md_struct{3};
    md4 = md_struct{4};
    md5 = md_struct{5};
    md6 = md_struct{6};
    md7 = md_struct{7};
    md8 = md_struct{8};
    md9 = md_struct{9};
    md10 = md_struct{10};
    md11 = md_struct{11};
    md12 = md_struct{12};
    md13 = md_struct{13};
    md14 = md_struct{14};
    md15 = md_struct{15};

    % Velocity from present day inversion
    vel_budd = md_budd.initialization.vel;
    vel1 = md1.initialization.vel;
    vel2 = md2.initialization.vel;
    vel3 = md3.initialization.vel;
    vel4 = md4.initialization.vel;
    vel5 = md5.initialization.vel;
    vel6 = md6.initialization.vel;
    vel7 = md7.initialization.vel;
    vel8 = md8.initialization.vel;
    vel9 = md9.initialization.vel;
    vel10 = md10.initialization.vel;
    vel11 = md11.initialization.vel;
    vel12 = md12.initialization.vel;
    vel13 = md13.initialization.vel;
    vel14 = md14.initialization.vel;
    vel15 = md15.initialization.vel;

    misfit_budd = vel_budd - md_budd.inversion.vel_obs;
    misfit1 = vel1 - md1.inversion.vel_obs;
    misfit2 = vel2 - md2.inversion.vel_obs;
    misfit3 = vel3 - md3.inversion.vel_obs;
    misfit4 = vel4 - md4.inversion.vel_obs;
    misfit5 = vel5 - md5.inversion.vel_obs;
    misfit6 = vel6 - md6.inversion.vel_obs;
    misfit7 = vel7 - md7.inversion.vel_obs;
    misfit8 = vel8 - md8.inversion.vel_obs;
    misfit9 = vel9 - md9.inversion.vel_obs;
    misfit10 = vel10 - md10.inversion.vel_obs;
    misfit11 = vel11 - md11.inversion.vel_obs;
    misfit12 = vel12 - md12.inversion.vel_obs;
    misfit13 = vel13 - md13.inversion.vel_obs;
    misfit14 = vel14 - md14.inversion.vel_obs;
    misfit15 = vel15 - md15.inversion.vel_obs;

    % Velocity from LIA SB solve
    vel_budd_lia = md_budd.results.StressbalanceSolution.Vel;
    vel1_lia = md1.results.StressbalanceSolution.Vel;
    vel2_lia = md2.results.StressbalanceSolution.Vel;
    vel3_lia = md3.results.StressbalanceSolution.Vel;
    vel4_lia = md4.results.StressbalanceSolution.Vel;
    vel5_lia = md5.results.StressbalanceSolution.Vel;
    vel6_lia = md6.results.StressbalanceSolution.Vel;
    vel7_lia = md7.results.StressbalanceSolution.Vel;
    vel8_lia = md8.results.StressbalanceSolution.Vel;
    vel9_lia = md9.results.StressbalanceSolution.Vel;
    vel10_lia = md10.results.StressbalanceSolution.Vel;
    vel11_lia = md11.results.StressbalanceSolution.Vel;
    vel12_lia = md12.results.StressbalanceSolution.Vel;
    vel13_lia = md13.results.StressbalanceSolution.Vel;
    vel14_lia = md14.results.StressbalanceSolution.Vel;
    vel15_lia = md15.results.StressbalanceSolution.Vel;

    misfit_budd(md_budd.inversion.vel_obs==0) = 0;
    misfit1(md1.inversion.vel_obs==0) = 0;
    misfit2(md2.inversion.vel_obs==0) = 0;
    misfit3(md3.inversion.vel_obs==0) = 0;
    misfit4(md4.inversion.vel_obs==0) = 0;
    misfit5(md5.inversion.vel_obs==0) = 0;
    misfit6(md6.inversion.vel_obs==0) = 0;
    misfit7(md7.inversion.vel_obs==0) = 0;
    misfit8(md8.inversion.vel_obs==0) = 0;
    misfit9(md9.inversion.vel_obs==0) = 0;
    misfit10(md10.inversion.vel_obs==0) = 0;
    misfit11(md11.inversion.vel_obs==0) = 0;
    misfit12(md12.inversion.vel_obs==0) = 0;
    misfit13(md13.inversion.vel_obs==0) = 0;
    misfit14(md14.inversion.vel_obs==0) = 0;
    misfit15(md15.inversion.vel_obs==0) = 0;


    % misfit_exp = '/home/eyhli/IceModeling/work/lia_kq/Exp/misfit_at_front.exp';
    % misfit_at_front_pos = find(ContourToNodes(md_budd.mesh.x, md_budd.mesh.y, misfit_exp, 2));
    maf_budd = md_budd_present.results.StressbalanceSolution.J(end, 1) / md_budd_present.inversion.cost_functions_coefficients(1,1) + md_budd_present.results.StressbalanceSolution.J(end, 2) ./ (md_budd_present.inversion.cost_functions_coefficients(1,2));
    maf1 = table.Var9(1) / md1.inversion.cost_functions_coefficients(1,1) + table.Var10(1) ./ (md1.inversion.cost_functions_coefficients(1,2));
    maf2 = table.Var9(2) / md2.inversion.cost_functions_coefficients(1,1) + table.Var10(2) ./ (md2.inversion.cost_functions_coefficients(1,2));
    maf3 = table.Var9(3) / md3.inversion.cost_functions_coefficients(1,1) + table.Var10(3) ./ (md3.inversion.cost_functions_coefficients(1,2));
    maf4 = table.Var9(4) / md4.inversion.cost_functions_coefficients(1,1) + table.Var10(4) ./ (md4.inversion.cost_functions_coefficients(1,2));
    maf5 = table.Var9(5) / md5.inversion.cost_functions_coefficients(1,1) + table.Var10(5) ./ (md5.inversion.cost_functions_coefficients(1,2));
    maf6 = table.Var9(6) / md6.inversion.cost_functions_coefficients(1,1) + table.Var10(6) ./ (md6.inversion.cost_functions_coefficients(1,2));
    maf7 = table.Var9(7) / md7.inversion.cost_functions_coefficients(1,1) + table.Var10(7) ./ (md7.inversion.cost_functions_coefficients(1,2));
    maf8 = table.Var9(8) / md8.inversion.cost_functions_coefficients(1,1) + table.Var10(8) ./ (md8.inversion.cost_functions_coefficients(1,2));
    maf9 = table.Var9(9) / md9.inversion.cost_functions_coefficients(1,1) + table.Var10(9) ./ (md9.inversion.cost_functions_coefficients(1,2));
    maf10 = table.Var9(10) / md10.inversion.cost_functions_coefficients(1,1) + table.Var10(10) ./ (md10.inversion.cost_functions_coefficients(1,2));
    maf11 = table.Var9(11) / md11.inversion.cost_functions_coefficients(1,1) + table.Var10(11) ./ (md11.inversion.cost_functions_coefficients(1,2));
    maf12 = table.Var9(12) / md12.inversion.cost_functions_coefficients(1,1) + table.Var10(12) ./ (md12.inversion.cost_functions_coefficients(1,2));
    maf13 = table.Var9(13) / md13.inversion.cost_functions_coefficients(1,1) + table.Var10(13) ./ (md13.inversion.cost_functions_coefficients(1,2));
    maf14 = table.Var9(14) / md14.inversion.cost_functions_coefficients(1,1) + table.Var10(14) ./ (md14.inversion.cost_functions_coefficients(1,2));
    maf15 = table.Var9(15) / md15.inversion.cost_functions_coefficients(1,1) + table.Var10(15) ./ (md15.inversion.cost_functions_coefficients(1,2));

    % md.inversion.cost_functions_coefficients(:,1) = coeffs(1); % 4000;
    % md.inversion.cost_functions_coefficients(:,2)
    title_budd = sprintf('Budd, J0*=%.1f (Present day)', maf_budd);
    title_1 = sprintf('J0*=%.1f, a=%.2g', maf1, md1.inversion.cost_functions_coefficients(1,3));
    title_2 = sprintf('J0*=%.1f, a=%.2g', maf2, md2.inversion.cost_functions_coefficients(1,3));
    title_3 = sprintf('J0*=%.1f, a=%.2g', maf3, md3.inversion.cost_functions_coefficients(1,3));
    title_4 = sprintf('J0*=%.1f, a=%.2g', maf4, md4.inversion.cost_functions_coefficients(1,3));
    title_5 = sprintf('J0*=%.1f, a=%.2g', maf5, md5.inversion.cost_functions_coefficients(1,3));
    title_6 = sprintf('J0*=%.1f, a=%.2g', maf6, md6.inversion.cost_functions_coefficients(1,3));
    title_7 = sprintf('J0*=%.1f, a=%.2g', maf7, md7.inversion.cost_functions_coefficients(1,3));
    title_8 = sprintf('J0*=%.1f, a=%.2g', maf8, md8.inversion.cost_functions_coefficients(1,3));
    title_9 = sprintf('J0*=%.1f, a=%.2g', maf9, md9.inversion.cost_functions_coefficients(1,3));
    title_10 = sprintf('J0*=%.1f, a=%.2g', maf10, md10.inversion.cost_functions_coefficients(1,3));
    title_11 = sprintf('J0*=%.1f, a=%.2g', maf11, md11.inversion.cost_functions_coefficients(1,3));
    title_12 = sprintf('J0*=%.1f, a=%.2g', maf12, md12.inversion.cost_functions_coefficients(1,3));
    title_13 = sprintf('J0*=%.1f, a=%.2g', maf13, md13.inversion.cost_functions_coefficients(1,3));
    title_14 = sprintf('J0*=%.1f, a=%.2g', maf14, md14.inversion.cost_functions_coefficients(1,3));
    title_15 = sprintf('J0*=%.1f, a=%.2g', maf15, md15.inversion.cost_functions_coefficients(1,3));

    plotmodel(md1,  ...
    'data', vel_budd, 'title', title_budd,  ...
    'data', vel1, 'title', title_1,  ...
    'data', vel2, 'title', title_2,  ...
    'data', vel3, 'title', title_3,  ...
    'data', vel4, 'title', title_4, ...
    'data', vel5, 'title', title_5, ...
    'data', vel6, 'title', title_6,  ...
    'data', vel7, 'title', title_7,  ...
    'data', vel8, 'title', title_8,  ...
    'data', vel9, 'title', title_9, ...
    'data', vel10, 'title', title_10, ...
    'data', vel11, 'title', title_11, ...
    'data', vel12, 'title', title_12, ...
    'data', vel13, 'title', title_13, ...
    'data', vel14, 'title', title_14, ...
    'data', vel15, 'title', title_15, ...
    'data', md_budd.inversion.vel_obs, 'title', 'Observed velocity', ...
    'axis#all', zoom, 'fontsize#all', 7, 'figure', 120); colormap('turbo'); 
    sgtitle(super_title,'Interpreter','latex');
    exportgraphics(gcf, sprintf("vel%d.png", i - 1), 'Resolution', res);

    plotmodel(md1,  ...
    'data', vel_budd_lia, 'title', title_budd,  ...
    'data', vel1_lia, 'title', title_1,  ...
    'data', vel2_lia, 'title', title_2,  ...
    'data', vel3_lia, 'title', title_3,  ...
    'data', vel4_lia, 'title', title_4, ...
    'data', vel5_lia, 'title', title_5, ...
    'data', vel6_lia, 'title', title_6,  ...
    'data', vel7_lia, 'title', title_7,  ...
    'data', vel8_lia, 'title', title_8,  ...
    'data', vel9_lia, 'title', title_9, ...
    'data', vel10_lia, 'title', title_10, ...
    'data', vel11_lia, 'title', title_11, ...
    'data', vel12_lia, 'title', title_12, ...
    'data', vel13_lia, 'title', title_13, ...
    'data', vel14_lia, 'title', title_14, ...
    'data', vel15_lia, 'title', title_15, ...
    'axis#all', zoom, 'fontsize#all', 7, 'figure', 121); colormap('turbo'); 
    sgtitle(super_title,'Interpreter','latex');
    exportgraphics(gcf, sprintf("vel_lia%d.png", i - 1), 'Resolution', res);

    plotmodel(md1, ...
    'data', misfit_budd, 'title', title_budd, ...
    'data', misfit1, 'title', title_1, ...
    'data', misfit2, 'title', title_2, ...
    'data', misfit3, 'title', title_3, ...
    'data', misfit4, 'title', title_4,...
    'data', misfit5, 'title', title_5, ...
    'data', misfit6, 'title', title_6, ...
    'data', misfit7, 'title', title_7, ...
    'data', misfit8, 'title', title_8, ...
    'data', misfit9, 'title', title_9,...
    'data', misfit10, 'title', title_10, ...
    'data', misfit11, 'title', title_11, ...
    'data', misfit12, 'title', title_12, ...
    'data', misfit13, 'title', title_13, ...
    'data', misfit14, 'title', title_14, ...
    'data', misfit15, 'title', title_15, ...
    'axis#all', zoom, 'fontsize#all', 7, 'figure', 122); colormap('turbo'); 
    sgtitle(super_title,'Interpreter','latex');
    exportgraphics(gcf, sprintf("misfit%d.png", i - 1), 'Resolution', res);

    plotmodel(md1, ...
    'data', misfit_budd, 'title', title_budd, ...
    'data', misfit1, 'title', title_1, ...
    'data', misfit2, 'title', title_2, ...
    'data', misfit3, 'title', title_3, ...
    'data', misfit4, 'title', title_4,...
    'data', misfit5, 'title', title_5, ...
    'data', misfit6, 'title', title_6, ...
    'data', misfit7, 'title', title_7, ...
    'data', misfit8, 'title', title_8, ...
    'data', misfit9, 'title', title_9,...
    'data', misfit10, 'title', title_10, ...
    'data', misfit11, 'title', title_11, ...
    'data', misfit12, 'title', title_12, ...
    'data', misfit13, 'title', title_13, ...
    'data', misfit14, 'title', title_14, ...
    'data', misfit15, 'title', title_15, ...
    'axis#all', zoom, 'fontsize#all', 7, 'caxis#all', cval(1, :), 'figure', 123); colormap('turbo');     
    sgtitle(super_title,'Interpreter','latex');    
    exportgraphics(gcf, sprintf("misfit_cval%d.png", i - 1), 'Resolution', res);

    % plotmodel(md1, ...
    % 'data', md_budd.results.StressbalanceSolution.Gradient1, 'title', title_budd, ...
    % 'data', md1.results.StressbalanceSolution.Gradient1, 'title', title_1, ...
    % 'data', md2.results.StressbalanceSolution.Gradient1, 'title', title_2, ...
    % 'data', md3.results.StressbalanceSolution.Gradient1, 'title', title_3, ...
    % 'data', md4.results.StressbalanceSolution.Gradient1, 'title', title_4, ...
    % 'data', md5.results.StressbalanceSolution.Gradient1, 'title', title_5, ...
    % 'data', md6.results.StressbalanceSolution.Gradient1, 'title', title_6, ...
    % 'data', md7.results.StressbalanceSolution.Gradient1, 'title', title_7, ...
    % 'data', md8.results.StressbalanceSolution.Gradient1, 'title', title_8, ...
    % 'data', md9.results.StressbalanceSolution.Gradient1, 'title', title_9, ...
    % 'data', md10.results.StressbalanceSolution.Gradient1, 'title', title_10, ...
    % 'data', md11.results.StressbalanceSolution.Gradient1, 'title', title_11, ...
    % 'data', md12.results.StressbalanceSolution.Gradient1, 'title', title_12, ...
    % 'data', md13.results.StressbalanceSolution.Gradient1, 'title', title_13, ...
    % 'data', md14.results.StressbalanceSolution.Gradient1, 'title', title_14, ...
    % 'data', md15.results.StressbalanceSolution.Gradient1, 'title', title_15, ...
    % 'axis#all', zoom, 'fontsize#all', 7, 'figure', 124); colormap('turbo'); exportgraphics(gcf, sprintf("gradient%d.png", i - 1), 'Resolution', res);
    % sgtitle(super_title,'Interpreter','latex')

    % plotmodel(md1, ...
    % 'data', md_budd.results.StressbalanceSolution.Gradient1, 'title', title_budd, ...
    % 'data', md1.results.StressbalanceSolution.Gradient1, 'title', title_1, ...
    % 'data', md2.results.StressbalanceSolution.Gradient1, 'title', title_2, ...
    % 'data', md3.results.StressbalanceSolution.Gradient1, 'title', title_3, ...
    % 'data', md4.results.StressbalanceSolution.Gradient1, 'title', title_4, ...
    % 'data', md5.results.StressbalanceSolution.Gradient1, 'title', title_5, ...
    % 'data', md6.results.StressbalanceSolution.Gradient1, 'title', title_6, ...
    % 'data', md7.results.StressbalanceSolution.Gradient1, 'title', title_7, ...
    % 'data', md8.results.StressbalanceSolution.Gradient1, 'title', title_8, ...
    % 'data', md9.results.StressbalanceSolution.Gradient1, 'title', title_9, ...
    % 'data', md10.results.StressbalanceSolution.Gradient1, 'title', title_10, ...
    % 'data', md11.results.StressbalanceSolution.Gradient1, 'title', title_11, ...
    % 'data', md12.results.StressbalanceSolution.Gradient1, 'title', title_12, ...
    % 'data', md13.results.StressbalanceSolution.Gradient1, 'title', title_13, ...
    % 'data', md14.results.StressbalanceSolution.Gradient1, 'title', title_14, ...
    % 'data', md15.results.StressbalanceSolution.Gradient1, 'title', title_15, ...
    % 'axis#all', zoom, 'fontsize#all', 7, 'caxis#all', cval(2, :), 'figure', 125); colormap('turbo'); exportgraphics(gcf, sprintf("gradient_cval%d.png", i - 1), 'Resolution', res);
    % sgtitle(super_title,'Interpreter','latex')

    plotmodel(md1, ...
    'data', md_budd.friction.coefficient, 'title', title_budd, ...
    'data', md1.friction.C, 'title', title_1, ...
    'data', md2.friction.C, 'title', title_2, ...
    'data', md3.friction.C, 'title', title_3, ...
    'data', md4.friction.C, 'title', title_4, ...
    'data', md5.friction.C, 'title', title_5, ...
    'data', md6.friction.C, 'title', title_6, ...
    'data', md7.friction.C, 'title', title_7, ...
    'data', md8.friction.C, 'title', title_8, ...
    'data', md9.friction.C, 'title', title_9, ...
    'data', md10.friction.C, 'title', title_10, ...
    'data', md11.friction.C, 'title', title_11, ...
    'data', md12.friction.C, 'title', title_12, ...
    'data', md13.friction.C, 'title', title_13, ...
    'data', md14.friction.C, 'title', title_14, ...
    'data', md15.friction.C, 'title', title_15, ...
    'axis#all', zoom, 'fontsize#all', 7, 'log#all', 10, 'caxis#all', [0.01 1e4], 'figure', 126); colormap('turbo'); sgtitle(super_title,'Interpreter','latex');
    exportgraphics(gcf, sprintf("friction_C_log%d.png", i - 1), 'Resolution', res);
    

end
